# 🚀 This workflow auto-syncs your fork with the upstream (https://github.com/wwwdageparty/da-cloud-commondatabase.git).
# 🧩 To enable it:
# 1. Copy this file to .github/workflows/sync.yml
# 2. Set a Personal Access Token secret named DA_SYNC_TOKEN with repo permissions
# 3. Modify the branch name if needed (default: main)
# 4. Done! It’ll sync daily at 2 AM UTC

name: Sync from Upstream da-cloud-commondatabase

on:
  schedule:
    - cron: "0 2 * * *"  # Every day at 2 AM UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.DA_SYNC_TOKEN }}

    - name: Detect default branch
      id: detect
      run: |
        branch=$(git symbolic-ref --short HEAD || echo main)
        echo "branch=$branch" >> $GITHUB_OUTPUT

    - name: Add upstream and fetch
      run: |
        git remote | grep upstream || git remote add upstream https://github.com/wwwdageparty/da-cloud-commondatabase.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout ${{ steps.detect.outputs.branch }}
        git merge upstream/${{ steps.detect.outputs.branch }} --no-edit || echo "No changes to merge"

    - name: Push updates back to your fork
      run: |
        git push origin ${{ steps.detect.outputs.branch }} || echo "No changes to push"
